### PR TITLE
X2 space fix

### PR DESCRIPTION
**Pull request by gwijthoff**
The current double space solution is still bothering me. (Ref #288.) There's no way this code...

`{{- if eq (add $index 1) $author_count -}}&nbsp;{{ printf " %s " (i18n "and") }} {{- else -}}, {{- end -}}`

...should produce this result!

Screen Shot 2022-08-03 at 3 42 10 PM

And, for some reason, that zombie space only rises from the dead on Render, or the production site, but not when serving locally. I know we still can't figure out how to remove the zombie space, but in this branch I replaced `&nbsp;` with an invisible, zero-width space character, copied and pasted from this [list of whitespace characters](https://qwerty.dev/whitespace/).

Let's see if it works on the Render site that this PR creates.

### CODE REVIEW

**Comment by gwijthoff** [comment]
@rlskoeser Better, but still not fixed with the zero-width space.

Screen Shot 2022-08-03 at 4 01 42 PM

**Comment by rlskoeser** [comment]
@gwijthoff the PR isn't showing any files changed, is this a glitch on GitHub's part?

**Comment by gwijthoff** [comment]
omg Rebecca I created the branch and the PR but didn't push my changes

**Comment by gwijthoff** [comment]
@rlskoeser ok ready for review

**Review by rlskoeser — APPROVED** [review]
Looks much better on render site.

Thanks for documenting it! FWIW, I checked and the invisible space is visible (sort of) in my code editor, so that's helpful.

**Pull request merged**
