### PR TITLE
Update styles for figure 3

### PR DESCRIPTION
**Pull request by thatbudakguy**
* Add underline styles based on Gissoo's designs
* Update caption based on Gian's notes
* Update citations based on Gian's notes

This is my attempt to harmonize Gian's notes with the design in Figma. The colors are a bit wacky, but I wanted to avoid overloading any of the colors used in figure 7.

## screenshot
Screenshot 2023-09-16 at 15 59 32

### CODE REVIEW

**Comment by rlskoeser** [comment]
@thatbudakguy do you want to keep this one in the dark purple? I think it may be more readable with the gray background.

What if we switch to gray and use the same color scheme but rotate the designs/patterns?

**Comment by thatbudakguy** [comment]
Yeah, I'd be happy to switch to gray and also switch up the colors or patterns for the underlines — I think the purple is going to be harder to read overall.

**Comment by rlskoeser** [comment]
@thatbudakguy oh good — I agree, the dark purple is not as readable

**Comment by rlskoeser** [comment]
@thatbudakguy can you handle updating from develop and resolving conflicts and adjusting the colors?

**Comment by thatbudakguy** [comment]
superseded by #364

**Pull request closed without merging**
