### PR TITLE
article & issue translation toggle and metadata

### PR DESCRIPTION
**Pull request by rlskoeser**
add translation toggle button and metadata for translated articles and translated issues

test with [translated article](https://startwords-dev-pr-242.onrender.com/issues/3/on-spanish-parrots/) on the render site for this pr

testing checklist:
- [x] translated article should have toggle buttons to switch back and forth between English and Spanish versions
- [x] toggle should indicate which language you are currently viewing
- [x] translated article metadata should include alternate links to all translations of the same article
- [x] articles without translations should not display the toggle
- [x] translated issue should have toggle buttons that behave similarly
- [x] untranslated issues should not have toggles

design review:
- [ ] please see what you think of the styles of the toggles; I implemented with CSS 3D effects but I'm not sure it's good enough
- [x] did I understand correctly which mode indicates the current language?

### CODE REVIEW

**Comment by rlskoeser** [comment]
It turned out it was easy to generalize this to a partial and include it on the issue detail page, so I've updated this PR to include that. Changes to styles will apply to both.

**Comment by gwijthoff** [comment]
@rlskoeser Is there any way to fix our [.txt character encoding](https://startwords-dev-pr-242.onrender.com/es/issues/3/on-spanish-parrots/index.txt)? It's atrocious with Spanish (not to mention typographer's quotes):

```
El espaÃ±ol es la segunda lengua mÃ¡s hablada en el mundo.
```

**Comment by rlskoeser** [comment]
> @rlskoeser Is there any way to fix our [.txt character encoding](https://startwords-dev-pr-242.onrender.com/es/issues/3/on-spanish-parrots/index.txt)? It's atrocious with Spanish (not to mention typographer's quotes):
> 
> ```
> El espaÃ±ol es la segunda lengua mÃ¡s hablada en el mundo.
> ```

It's something specific to Render! I've looked before and haven't seen any settings to do anything about this.

**Comment by rlskoeser** [comment]
> Also on .txt -- article metadata appears in English at the top of the file, but the article body text is in Spanish.

oh, good catch! I didn't even look at that template.

Should the text version note that an article is available in translation? Any suggestions for how you'd like it to look?

**Comment by gwijthoff** [comment]
> It's something specific to Render! 

@rlskoeser oh that's right! We talked about this before. Nevermind.

> Should the text version note that an article is available in translation?

Maybe beneath the article URL, "Article available in: English, Español"

**Comment by gwijthoff** [comment]
This is annoying, but "Ediciónes" doesn't quite fit inside the nav box. The full word is still legible (the 's' just barely cut off) though. What do you think, @gissoo ?

Screen Shot 2022-03-24 at 3 38 48 PM

**Comment by rlskoeser** [comment]
> This is annoying, but "Ediciónes" doesn't quite fit inside the nav box. The full word is still legible (the 's' just barely cut off) though. What do you think, @gissoo ?

@gwijthoff I agree, it's very annoying! I have an attempted fix in this PR: #243

**Comment by gwijthoff** [comment]
@rlskoeser two steps ahead! We can discuss nav stuff over there.

**Review by gwijthoff — APPROVED** [review]
All the things on my checklist are good to go.

**Comment by rlskoeser** [comment]
occurs to me tooltips and aria labels for the language toggles would be good too — how about "read this article in [language]" ?

**Comment by gissoo** [comment]
@rlskoeser I think functionally everything looks fine, except I'm not sure I understand this at all: " translated article metadata should include alternate links to all translations of the same article" 

Regarding the styles:
- I think the style of the toggles are not clear enough, below is the design on Figma: The edges on the right and the bottom are set to make it clearer which is active and which is not. 
Screen Shot 2022-03-31 at 9 27 29 PM

This is the CSS version I see in the browser now – it's not matching the designs based on my comment above, also there is a bit of gap between the two toggles. 
Screen Shot 2022-03-31 at 9 28 40 PM


Same thing for when ES is selected – this is the design below vs. the CSS version 
Screen Shot 2022-03-31 at 9 31 55 PM


CSS version: Also the two toggles are not quite aligned, the one on the right is standing a bit lower here. 
Screen Shot 2022-03-31 at 9 30 02 PM


- Could you please remove the dashed outline that appears on click? I know it's everywhere but it's really bothering me for the on click interaction (not the keyboard of course)

**Comment by rlskoeser** [comment]
@gissoo thanks for reviewing! I had trouble getting the CSS 3D version to line up exactly, it's very fiddly; should we just use images so we can make sure it looks right? If you agree, please provide background images for selected and deselected states.

I can adjust the focus styles — I remember now there is a keyboard focus selector now. Do you only want it on this element or should apply elsewhere/everywhere?

**Comment by rlskoeser** [comment]
merging since the functionality is working and we don't want this to be a blocker; will fine-tune the styles for the toggle buttons in another round

**Pull request merged**
