### PR TITLE
Use ascii art version of logotype in article plain text template

### PR DESCRIPTION
**Pull request by rlskoeser**
I used an online ascii art generator to create an ascii version of the _Startwords_ logotype, and added it to our article text template. It's a bit wider than the previous version, but I think not too wide.

@gissoo FYI I made the logotype black and white and darkened it a bit because it wasn't showing up at all with the light color. Let me know if that's a concern.

### CODE REVIEW

**Comment by thatbudakguy** [comment]
this is super cool, I love the way this more petscii-styled one gives it a fragmentary/digital look!

**Comment by gwijthoff** [comment]
Welp, today I learned what PETSCII is. Looks amazing!

**Comment by gissoo** [comment]
@rlskoeser Sorry I missed this! How can I view it?

**Comment by rlskoeser** [comment]
@gissoo it's deployed now, so check it out on the text version of one of our draft articles! https://startwords.cdh.princeton.edu/issues/1/data-beyond-vision/index.txt

**Comment by gwijthoff** [comment]
@gissoo arg, sorry I merged before you reviewed

**Comment by gissoo** [comment]
@rlskoeser omg!!! WHATTT Looks so interstellar =O 
Awesome! thank you!! 
@gwijthoff No worries!!

**Pull request merged**
