### PR TITLE
simplify main nav styles

### PR DESCRIPTION
**Pull request by rlskoeser**
When I started working on site localization, including supporting translation for "Issues" in the main nav, I noticed that the styles were very hard-coded and not sized relative to the content of the text.

This is my attempt to simplify the nav styles so it resizes properly to the content..

The one thing I couldn't figure out how to replicate is the way the issues button slides over when you click — right now I have the white border but the text doesn't move, so it's inconsistent with the SW logo, which does move. I wanted to hear if this is important before spending more time on it.

## review notes:
- [x] compare nav on [spanish issue list](https://startwords-dev-pr-243.onrender.com/es/issues/) and [english issue list](https://startwords-dev-pr-243.onrender.com/issues/) and see that it scales correctly to fit the word
- [x] check behavior across the site for interactions/display; have I missed or broken anything?
- [ ] issues link text slides over when focused/clicked (same as it used to)
- [ ] issues link text now slides over when clicked in Safari

### CODE REVIEW

**Comment by gwijthoff** [comment]
This is potentially very nit-picky, but the red and purple polygons are now out of joint. That red elbow neatly met the vertical edge of the purple before.

Screen Shot 2022-03-24 at 4 08 09 PM

**Comment by gwijthoff** [comment]
One thing I noticed is that the [404 page](https://startwords-dev-pr-243.onrender.com/es/acerca-de/) at the `/es/` URL isn't displaying Spanish text. Otherwise, I think this new elastic functionality for the nav depending on the text length looks great.

I'll leave it up to @gissoo to decide whether it's worth more of your time to make sure the button slides over on the Spanish version.

**Review by gwijthoff — APPROVED** [review]

**Comment by rlskoeser** [comment]
> One thing I noticed is that the [404 page](https://startwords-dev-pr-243.onrender.com/es/acerca-de/) at the `/es/` URL isn't displaying Spanish text. Otherwise, I think this new elastic functionality for the nav depending on the text length looks great.

I missed your comment about the translated 404 — I saw some comments on the Hugo forums or github issues, localized 404 page may not be supported or may be harder. It would be nice, but not sure how much it matters.

**Comment by gissoo** [comment]
@rlskoeser @gwijthoff I don't see the problem with the buttons not aligning in the nav anymore – everything looks perfect from my side with this. I would argue a 404 is clear and probably not urgent or necessary to be translated.

**Comment by gissoo** [comment]
@rlskoeser the only thing I notice about " check behavior across the site for interactions/display; have I missed or broken anything?" – is that when you go to the homepage from the ES version of the issue list page the "About" preview is missing from the homepage.

**Comment by rlskoeser** [comment]
Finally adjusted the new version of the clip path so that the "issues" text slides over on click like it used to.

Bonus, in the process I fixed a bug we didn't know we had in Safari — had to add `:active` in addition to the `:focus` we already had.

@gwijthoff could you confirm? I added two more checklist items to the review. If it passes, you can merge.

**Comment by gwijthoff** [comment]
@rlskoeser it slides over even more noticeably than before. Nice.

Issue 3: now with more slideyness!

**Pull request merged**
