### PR TITLE
article language indicator

### PR DESCRIPTION
**Pull request by rlskoeser**
in this pr:

- refactor language indicator logic from issue list to a partial
- use available languages partial for feature articles and snippets on home page and issue list
- implement dark-background styles for language indicator chips 
- translations for available languages text

testing checklist:
- [x] issue list displays language indicators for each article; see [issue 3](https://startwords-dev-pr-245.onrender.com/issues/3/#features)
- [x] issue list displays language indicators for snippets; see [issue 2](https://startwords-dev-pr-245.onrender.com/issues/2/#features)
- [x] language indicators also display for articles on the [homepage](https://startwords-dev-pr-245.onrender.com/)

design review checklist:
- [x] language chip styles implemented correctly for dark background
- [ ] spacing for language chips correct on feature articles
- [ ] spacing for language chips looks ok for snippets

### CODE REVIEW

**Comment by gissoo** [comment]
@rlskoeser everything looks great! except the spacing of the chips:
the chips are about:
- 4px away from each other (for when there is more than one)
- 16px below the article title 
- 18px above the author 1's name
Screen Shot 2022-04-01 at 5 39 56 PM

**Comment by gwijthoff** [comment]
Looks great @rlskoeser! My one comment is that the [homepage](https://startwords-dev-pr-245.onrender.com/) displays Spanish by default with no option to toggle to English. But that's probably just not covered in this PR?

**Comment by rlskoeser** [comment]
@gwijthoff good question about the homepage — I think we may need an update to the logic to pull the correct issue, and I'm not sure it's tracked anywhere, but I'd like to get some of the in-progress work merged first and see!

**Review by gwijthoff — APPROVED** [review]

**Comment by rlskoeser** [comment]
@gissoo I've adjusted spacing based on your comments. Do you want to review again or ok to merge?

**Comment by gissoo** [comment]
> @gissoo I've adjusted spacing based on your comments. Do you want to review again or ok to merge?
>

@rlskoeser no it's totally fine, no need to review again, thanks so much!!!

**Pull request merged**
