### PR TITLE
Preliminary markup and styles for figure 7 #346

### PR DESCRIPTION
**Pull request by rlskoeser**

### CODE REVIEW

**Comment by rlskoeser** [comment]
@thatbudakguy this is a preliminary implementation of Gissoo's designs for your figure 7. Could you review to check that I've restructured the html properly and have all the correct terms matched up?  (Comments on the approach are welcome if you have time & interest.)

**Comment by rlskoeser** [comment]
@thatbudakguy @gissoo ok, I've made some progress on the styles but not fully working. When I adjusted the styles for mobile I messed up something with the padding for some of the underlines on desktop and it's late on a Friday so I'm going to leave it for now.   

@thatbudakguy any ideas how to do the full-width white and gray stripes on desktop? Do you think a background gradient would work?

**Comment by thatbudakguy** [comment]
re: stripes, haven't tried this out, but could you use the same approach as the purple interludes? i.e. a `::before` pseudo-element that is set to `width: 100vw;` (looks like)

**Comment by thatbudakguy** [comment]
see #352 for my suggestions.

**Comment by gwijthoff** [comment]
This looks phenomenal! Thanks for your work on figure 7, everyone.

**Comment by gwijthoff** [comment]
@thatbudakguy sorry, getting a little lost in all the versions here. Can you resolve the conflict above then merge the PR? I'm not sure which should be used: the HTML & caption text from `develop` or from `sw4-feature1-fig7`.

**Comment by thatbudakguy** [comment]
I don't have write access to this repo, so unfortunately I can't do that...I'm happy to give it a shot if you grant me access as a collaborator, or @rlskoeser could resolve them.

**Pull request merged**
