### PR TITLE
Add print css for generating PDFs with WeasyPrint

### PR DESCRIPTION
**Pull request by rlskoeser**
Adds print css for articles tailored specifically to WeasyPrint. 

@thatbudakguy thought you could review the code and then Grant could test generating the PDF and inspecting it. If you want to generate test PDFs yourself, it should be a matter of installing and running weasyprint:
- install weasyprint and depedencies per [weasyprint installation instructions](https://weasyprint.readthedocs.io/en/stable/install.html)
- weasyprint url outputfile.pdf

FYI, running WeasyPrint on our articles results in a lot of warnings because we're using a lot of things that weasyprint doesn't support. I think this is ok? I tried making some sections screen only, but it didn't seem to help that much with the warnings, and I was worried about losing styles that we actually want.

(Not sure where this should be documented — defer to Grant, since I think he'll be the one actually doing it.)

### CODE REVIEW

**Comment by rlskoeser** [comment]
Forgot to note: Gissoo and I are still fine-tuning some of the styles, but I thought this was far enough along that you could review for general approach and functionality.

I think there will be more things we'll have to think about how to handle (for example: do we want some kind of fall-back content for the interactive content like the deep zoom & 3d viewer?), but figured we could revise/add more styles when we're ready.

**Comment by gwijthoff** [comment]
@rlskoeser on documentation: so far there will be a theme README, and then a style guide for authors and guest editors, correct?<sup>[1](#myfootnote1)</sup> Seems like documenting the Weasyprint error messages belongs in the theme documentation, since it's an issue that will apply most to people who re-use this code, or who take over general editorship of the journal after me.

Ready to test that PDF functionality whenever @thatbudakguy has had a chance to review the code. As editor, will I manually run the weasyprint command in my terminal and then upload the file to the site? Or will the PDF be auto-generated with each Hugo build upon editing the underlying markdown file?

*******

<sup><a name="myfootnote1">1</a></sup> Did I tell you all that I've been thinking about inviting guest editors for future issues, who will write the issue description and work with the authors, or has that thought not yet left my brain?

**Comment by rlskoeser** [comment]
😆  Did not know you could put markdown footnotes in github comments! 🤯  (have I shared that I'm thinking more and more in footnotes?)

You're welcome to take it for a spin now if you want if you have time — I just thought it might be a clearer way to separate review and testing.  I think the basic functionality and how you use it isn't likely to change.

Right now there's no automation. As far as I've been able to figure out, there isn't actually any way to have Hugo generate the PDFs for us — but I think that's ok, since I think we decided we want to generate the PDFs when the articles are finalized, upload them to Zenodo, and then link to the PDF on Zenodo. We have some issues related to automating that in the future (#6 #35) but I don't think we know enough or have time to automate it yet.

Will guest editors need to do work with technical aspects also? Interesting.

**Comment by gwijthoff** [comment]
@rlskoeser I cheated, it's HTML not markdown.

```
<sup>[1](#myfootnote1)</sup>

<sup><a name="myfootnote1">1</a></sup> Note text here
```

Not sure the degree to which guest editors will need to engage with the technical aspects of the site. I suppose it will depend on the issue topic and what they'd like to do with it. Will be exciting to see!

**Comment by rlskoeser** [comment]
@gwijthoff I saw you "cheated" when I tried to duplicate it. 😁  Thx for sharing.

Agreed, will be exciting to get guest editors involved!

**Comment by gwijthoff** [comment]
@rlskoeser When I try to PDFify "Data Beyond Vision" using this command:

```$ weasyprint https://startwords.cdh.princeton.edu/issues/1/data-beyond-vision/ test1.pdf```

[I get this output](https://gist.github.com/gwijthoff/fdb1298e995f05706c236fc326266e7c), with no PDF produced.

**Comment by rlskoeser** [comment]
@gwijthoff until this branch is merged, you should test on a local version of the site running on this branch (which might be reason enough to wait!). However! Your errors indicate some of the dependencies are missing, which is my oversight — I should have linked to the [weasyprint installation instructions](https://weasyprint.readthedocs.io/en/stable/install.html) because there are indeed other dependencies required.

**Comment by gwijthoff** [comment]
Ok, installed all of Weasyprints dependencies, served this branch locally, and it (mainly) works! So exciting to see. The one question mark is the handling of the contextual notes as endnotes. See the last page [in my PDF.](https://www.dropbox.com/s/k73m828gja8usqz/dbv_gwythoff_test1.pdf?dl=0)

**Comment by rlskoeser** [comment]
@gwijthoff that's a regression, the endnotes shouldn't look like that! Sorry I didn't catch it — I bet when I merged in all the updates from master I missed something. I'll look into it.

**Pull request merged**
