### PR TITLE
Try out alternate approach to article text output

### PR DESCRIPTION
**Pull request by rlskoeser**
ref #316

Preliminary work to explore an alternate approach for generating the plain-text version of articles.

I've added `.txt` templates for our figure and pull quote shortcodes, and updated the Underwood article to use them. As you can see, we no longer have to duplicate the plain text version of the figure in the article source, we can generate it from the template.

If we go with this approach we'd have to rewrite or add regexes to run against html instead of markdown (unless we can find a better approach than that).  From my experimentation, I think that this approach might also solve the character bug in #303 

Please review the new text templates, the corresponding changes to the Underwood article, and the text version of that article on the Render PR site and provide feedback on whether you think this direction is worth pursuing.

### CODE REVIEW

**Review by gwijthoff — COMMENTED** [review]
Brilliant solution to replacing those janky regexes! I love having the pull quotes in the .txt output. And that would be great if this approach solves the #303 character bug. When you say "rewrite or add regexes to run against html instead of markdown," do you mean find a way to translate the `<i>html<i>` to `*markdown*` output in the .txt file? We could strip out all html markup, but I feel like it's important to maintain the markdown in the .txt since it's both human readable and machine executable, and keeps intact all of the authorial intent in the piece.

**Comment by rlskoeser** [comment]
@gwijthoff yes, was thinking we'd need to write new regexes to convert the html to whatever we want the text to look like — similar to what we do now, converting markdown footnotes into [NOTE 2]. I wish there was a better option than regexes, but at least maybe text versions of shortcodes will improve things some.

**Comment by gwijthoff** [comment]
@rlskoeser I agree that this would be a marginal improvement over our current TXT output and is worth pursuing. Not a must-have for Issue 4 in case your capacity is tight next week, but it would definitely be great.

**Comment by rlskoeser** [comment]
closing this PR for now since we don't have capacity to investigate further; will keep the branch and the issue in the icebox to track the initial work

**Pull request closed without merging**
